let questions = { "questions": [
    { "question": "Who won the 2018 FIFA World Cup?", "answer": "France" },
    { "question": "Which country hosted the 1998 FIFA World Cup?", "answer": "France" },
    { "question": "Who is known as 'The Egyptian King' in football?", "answer": "Mohamed Salah" },
    { "question": "Which player is known as 'CR7'?", "answer": "Cristiano Ronaldo" },
    { "question": "Which club did Lionel Messi play for before joining Paris Saint-Germain?", "answer": "Barcelona" },
    { "question": "Which team won the 2020 UEFA Champions League?", "answer": "Bayern Munich" },
    { "question": "Which country has won the most World Cup titles?", "answer": "Brazil" },
    { "question": "Who is the all-time top scorer in the Premier League?", "answer": "Harry Kane" },
    { "question": "Which player is known as 'The Pharaoh'?", "answer": "Mohamed Salah" },
    { "question": "Who is the manager of Manchester City as of 2024?", "answer": "Pep Guardiola" },
    { "question": "Which country won the 2014 FIFA World Cup?", "answer": "Germany" },
    { "question": "Who holds the record for the most goals in World Cup history?", "answer": "Marta" },
    { "question": "Which country won the UEFA Euro 2020?", "answer": "Italy" },
    { "question": "Who won the Ballon d'Or in 2023?", "answer": "Lionel Messi" },
    { "question": "Which team won the Premier League in the 2022/2023 season?", "answer": "Manchester City" },
    { "question": "Who was the first footballer to win five Ballon d'Or awards?", "answer": "Cristiano Ronaldo" },
    { "question": "Who won the 2022 FIFA World Cup?", "answer": "Argentina" },
    { "question": "Which club has the most UEFA Champions League titles?", "answer": "Real Madrid" },
    { "question": "Which country hosted the 2014 FIFA World Cup?", "answer": "Brazil" },
    { "question": "Which footballer is known as 'The Special One'?", "answer": "Jose Mourinho" },
    { "question": "Which country won the 2010 FIFA World Cup?", "answer": "Spain" },
    { "question": "Who is the all-time top scorer in La Liga?", "answer": "Lionel Messi" },
    { "question": "Which team won the 2022 FIFA World Cup final?", "answer": "Argentina" },
    { "question": "Which country has the most Copa America titles?", "answer": "Uruguay" },
    { "question": "Who is the all-time top scorer for Manchester United?", "answer": "Wayne Rooney" },
    { "question": "Who won the 2012 UEFA Champions League?", "answer": "Chelsea" },
    { "question": "Who holds the record for the most goals in a single season in the Premier League?", "answer": "Erling Haaland" },
    { "question": "Who is the only player to have won the Ballon d'Or, FIFA World Cup, and the UEFA Champions League in the same year?", "answer": "Lionel Messi" },
    { "question": "Which country won the first FIFA World Cup in 1930?", "answer": "Uruguay" },
    { "question": "Who is the all-time top scorer in the Bundesliga?", "answer": "Gerd Müller" },
    { "question": "Who is known as 'The King of the Dribble'?", "answer": "Diego Maradona" },
    { "question": "Which team has won the most FA Cups?", "answer": "Arsenal" },
    { "question": "Who is the only player to have won the European Golden Shoe four times?", "answer": "Lionel Messi" },
    { "question": "Which club is nicknamed 'The Red Devils'?", "answer": "Manchester United" },
    { "question": "Who is the all-time top scorer in the Italian Serie A?", "answer": "Cristiano Ronaldo" },
    { "question": "Who won the 2021 Copa America?", "answer": "Argentina" },
    { "question": "Which country won the first UEFA Euro Championship in 1960?", "answer": "Soviet Union" },
    { "question": "Who won the 2016 UEFA Euro Championship?", "answer": "Portugal" },
    { "question": "Who is the all-time top scorer in the French Ligue 1?", "answer": "Thierry Henry" },
    { "question": "Which player has the most international goals for Brazil?", "answer": "Neymar" },
    { "question": "Which club has won the most La Liga titles?", "answer": "Real Madrid" },
    { "question": "Who is the top scorer for the German national football team?", "answer": "Miroslav Klose" },
    { "question": "Which country hosted the 2002 FIFA World Cup?", "answer": "South Korea and Japan" },
    { "question": "Who was the first player to reach 1000 career goals?", "answer": "Pele" },
    { "question": "Who is the youngest player to score in a World Cup?", "answer": "Pele" },
    { "question": "Which team won the 2015 Women's World Cup?", "answer": "United States" },
    { "question": "Who is the all-time top scorer in the UEFA Champions League?", "answer": "Cristiano Ronaldo" },
    { "question": "Who was the manager of England during the 1966 World Cup?", "answer": "Alf Ramsey" },
    { "question": "Which country has won the most FIFA Women's World Cup titles?", "answer": "United States" },
    { "question": "Who is the all-time top scorer for Barcelona?", "answer": "Lionel Messi" },
    { "question": "Which player holds the record for the most appearances in the Premier League?", "answer": "Ryan Giggs" },
    { "question": "Which club has the most UEFA Europa League titles?", "answer": "Sevilla" },
    { "question": "Which country won the 1998 FIFA World Cup?", "answer": "France" },
    { "question": "Which team has won the most Copa del Rey titles?", "answer": "Barcelona" },
    { "question": "Who is the most expensive football player in the world?", "answer": "Neymar" },
    { "question": "Which country won the 2006 FIFA World Cup?", "answer": "Italy" },
    { "question": "Who won the 2019 UEFA Champions League?", "answer": "Liverpool" },
    { "question": "Who is known as 'The Little Magician'?", "answer": "Lionel Messi" },
    { "question": "Who is the all-time top scorer in the English Premier League?", "answer": "Harry Kane" },
    { "question": "Which country has won the most Africa Cup of Nations titles?", "answer": "Egypt" },
    { "question": "Which player has the most appearances in the history of the World Cup?", "answer": "Lothar Matthäus" },
    { "question": "Who won the 1994 FIFA World Cup?", "answer": "Brazil" },
    { "question": "Which team won the 2023 FIFA Women's World Cup?", "answer": "Spain" },
    { "question": "Which footballer is famous for the 'Hand of God' goal?", "answer": "Diego Maradona" },
    { "question": "Which player won the 2022 Ballon d'Or?", "answer": "Karim Benzema" },
    { "question": "Who scored the fastest goal in World Cup history?", "answer": "Hakan Şükür" },
    { "question": "Who is the all-time top scorer for the Argentina national team?", "answer": "Lionel Messi" },
    { "question": "Which country hosted the 2010 FIFA World Cup?", "answer": "South Africa" },
    { "question": "Who scored the winning goal in the 2014 World Cup final?", "answer": "Mario Götze" },
    { "question": "Which country won the 2000 UEFA Euro Championship?", "answer": "France" },
    { "question": "Who is the all-time top scorer for Bayern Munich?", "answer": "Gerd Müller" },
    { "question": "Which country has the most Asian Cup titles?", "answer": "Japan" },
    { "question": "Who won the 2011 Copa America?", "answer": "Uruguay" },
    { "question": "Which club has the most Serie A titles?", "answer": "Juventus" },
    { "question": "Who is the top scorer in the history of the FA Cup?", "answer": "Ian Rush" },
    { "question": "Who is the all-time top scorer for the Chelsea football club?", "answer": "Frank Lampard" },
    { "question": "Which country hosted the 2022 FIFA World Cup?", "answer": "Qatar" },
    { "question": "Who is the only goalkeeper to have won the Ballon d'Or?", "answer": "Lev Yashin" },
    { "question": "Who scored the most goals in a single Premier League season?", "answer": "Erling Haaland" },
    { "question": "Which country won the 1982 FIFA World Cup?", "answer": "Italy" },
    { "question": "Who won the 2017 UEFA Champions League?", "answer": "Real Madrid" },
    { "question": "Which football club is nicknamed 'The Gunners'?", "answer": "Arsenal" },
    { "question": "Which country won the 1966 FIFA World Cup?", "answer": "England" },
    { "question": "Who is the all-time top scorer for Juventus?", "answer": "Cristiano Ronaldo" }
  ]
};


let firstQuestion = questions.questions[0].question;
let firstAnswer = questions.questions[0].answer;

console.log("First Question:", firstQuestion);
console.log("First Answer:", firstAnswer);